### ISSUE TITLE
Update How to Install Getting Python on Windows notes

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/IntroToPython-2014#113]
slides_sources/source/supplements/python_for_windows.rst

**Comment by PythonCHB** [comment]
I've done a quick update.

But no Windows box to test it out -- could someone give it a try????

**Comment by codedragon** [comment]
I'll follow the instructions tomorrow on a windows box, but I know I would like to change the instructions so everyone installs Git Bash, unless they can confidently use DOS or powershell with no help from us. Assuming that's fine with everyone else...

**Comment by PythonCHB** [comment]
I think that's a fine idea:

If you are comfortable with the DOS box or Powereshell, use that otherwise, use git Bash.

Do make sure that iPython runs fine in gitBash

**Comment by PythonCHB** [comment]
@codedragon: are you happy with this?

**Comment by PythonCHB** [comment]
Fixed a couple typos, and it looks good to me.

**Comment by codedragon** [comment]
Cool, thanks.

On Mon, Oct 5, 2015 at 8:44 PM, Christopher H.Barker, PhD <
notifications@github.com> wrote:

> Fixed a couple typos, and it looks good to me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWPCE-PythonCert/IntroToPython/issues/113#issuecomment-145734502
> .

## 

Maria Mckinley
Software Developer with Bonus SysAdmin Experience
www.mariakathryn.net
www.linkedin.com/in/mariamckinley

_NOTICE:_ Due to Presidential Executive Orders still not rescinded by
President Obama, the National Security Agency may have read this email
without warning, warrant, or notice, and certainly without probable cause.
They may do this without any judicial or legislative oversight. Click here
to learn more about current US laws and your rights
http://www.aclu.org/national-security/surveillance-privacy.
